### ISSUE TITLE
How to use ngu-app-shell with @angular/cli

### ISSUE THREAD

**Issue by marcincichocki** [alxhub/io17#11]
I try to follow excellent talk you guys gave to generate basic appliation shell, but I'm getting an error:

```bash
ngu-app-shell --module src/app/app.module.ts

.../node_modules/ts-node/src/index.ts:159
      throw new TSError(configDiagnostics)
            ^
TSError: ⨯ Unable to compile TypeScript
The 'files' list in config file 'tsconfig.json' is empty. (18002)
    at load (.../node_modules/ts-node/src/index.ts:159:13)
    at service (.../node_modules/ts-node/src/index.ts:285:32)
    at Object.register (.../node_modules/ts-node/src/index.ts:316:5)
    at Object.<anonymous> (.../node_modules/ts-node/src/_bin.ts:157:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```
Project was generated with `@angular/cli`

**Comment by webmaxru** [comment]
I wrote a notice about ng-pwa-tools. @alxhub, please review this page: https://docs.google.com/document/d/1F0e0ROaZUnTFftmC0XovpREHWHjcXa4CggiFlmifjhw/edit#heading=h.yoinubqorb1g

**Comment by markgoho** [comment]
@webmaxru Maxim, thank you _so_ much for weighing in here. We all want to see this project succeed -- let's work together to make it _awesome_ 💯

**Comment by alxhub** [comment]
@webmaxru looks good to me!

In general I think it'd be very useful to document supported/unsupported cases. The tooling can then be made smarter by making it detect things which won't work and let you know about them.
